from __future__ import annotations


from madeira_threads import MADEIRA_THREADS


FLORIANI_THREADS = [
    {"brand": "Floriani", "number": 'PF 1107', "name": 'Shrimp', "color": '#ed4594'},
    {"brand": "Floriani", "number": 'PF 155', "name": 'Martha Washington', "color": '#e6253e'},
    {"brand": "Floriani", "number": 'PF 156', "name": 'Persimmon', "color": '#e62237'},
    {"brand": "Floriani", "number": 'PF 700', "name": 'Mars Red', "color": '#e41c17'},
    {"brand": "Floriani", "number": 'PF 702', "name": 'Fire Engine Red', "color": '#e21916'},
    {"brand": "Floriani", "number": 'PF 703', "name": 'Ruby Red', "color": '#e62423'},
    {"brand": "Floriani", "number": 'PF 1081', "name": 'Pink Rose', "color": '#f9c8cd'},
    {"brand": "Floriani", "number": 'PF 1082', "name": 'Rose Cerise', "color": '#fa8f9c'},
    {"brand": "Floriani", "number": 'PF 1083', "name": 'Begonia', "color": '#ec3f66'},
    {"brand": "Floriani", "number": 'PF 1084', "name": 'Hibiscus', "color": '#e61e3d'},
    {"brand": "Floriani", "number": 'PF 1085', "name": 'Violet Red', "color": '#df1d32'},
    {"brand": "Floriani", "number": 'PF 1086', "name": 'Raspberry', "color": '#cd1220'},
    {"brand": "Floriani", "number": 'PF 083', "name": 'Raspberry Rhapsody', "color": '#da183c'},
    {"brand": "Floriani", "number": 'PF 023', "name": 'Shocking Pink', "color": '#d51537'},
    {"brand": "Floriani", "number": 'PF Y40', "name": 'Pink Passion', "color": '#e2265c'},
    {"brand": "Floriani", "number": 'PF 110', "name": 'Pale Peach', "color": '#f4d1cc'},
    {"brand": "Floriani", "number": 'PF 111', "name": 'Light Peach', "color": '#faddcb'},
    {"brand": "Floriani", "number": 'PF 170', "name": 'Cantaloupe', "color": '#f67d56'},
    {"brand": "Floriani", "number": 'PF 172', "name": 'Orange', "color": '#ec392a'},
    {"brand": "Floriani", "number": 'PF 1051', "name": 'Singapore Sunset', "color": '#d91f1c'},
    {"brand": "Floriani", "number": 'PF 1053', "name": 'Saffron', "color": '#e41e1a'},
    {"brand": "Floriani", "number": 'PF 188', "name": 'Iron Rust', "color": '#e2192d'},
    {"brand": "Floriani", "number": 'PF 190', "name": 'Scarlet', "color": '#b01114'},
    {"brand": "Floriani", "number": 'PF 192', "name": 'Deep Rust', "color": '#991213'},
    {"brand": "Floriani", "number": 'PF 194', "name": 'Burgundy', "color": '#911215'},
    {"brand": "Floriani", "number": 'PF 196', "name": 'Old Roseleaf', "color": '#8e1c21'},
    {"brand": "Floriani", "number": 'PF 198', "name": 'Wine', "color": '#72171d'},
    {"brand": "Floriani", "number": 'PF 167', "name": 'Deep Mauve', "color": '#a4282d'},
    {"brand": "Floriani", "number": 'PF 165', "name": 'Mauve', "color": '#c25a5a'},
    {"brand": "Floriani", "number": 'PF 163', "name": 'Soapstone', "color": '#fbc9c0'},
    {"brand": "Floriani", "number": 'PF 1021', "name": 'Buff', "color": '#f8e5dc'},
    {"brand": "Floriani", "number": 'PF 140', "name": 'Light Coral', "color": '#faccc4'},
    {"brand": "Floriani", "number": 'PF 141', "name": 'Coral', "color": '#f9988c'},
    {"brand": "Floriani", "number": 'PF 143', "name": 'Dark Coral', "color": '#f6695a'},
    {"brand": "Floriani", "number": 'PF 145', "name": 'Rust', "color": '#e93235'},
    {"brand": "Floriani", "number": 'PF 147', "name": 'Terra Cotta', "color": '#e5212a'},
    {"brand": "Floriani", "number": 'PF 1900', "name": 'Petunia', "color": '#fabfc4'},
    {"brand": "Floriani", "number": 'PF 1902', "name": 'Roseleaf', "color": '#e57481'},
    {"brand": "Floriani", "number": 'PF 1904', "name": 'Pansies Perfections', "color": '#db5661'},
    {"brand": "Floriani", "number": 'PF 1906', "name": 'Purple Pansies', "color": '#d13949'},
    {"brand": "Floriani", "number": 'PF 1908', "name": 'Dark Pansies', "color": '#b21f38'},
    {"brand": "Floriani", "number": 'PF 1910', "name": 'Paternina', "color": '#832132'},
    {"brand": "Floriani", "number": 'PF 100', "name": 'Oyster', "color": '#f0e7e8'},
    {"brand": "Floriani", "number": 'PF 151', "name": 'Baby Pink', "color": '#f6cad5'},
    {"brand": "Floriani", "number": 'PF 153', "name": 'Dusty Rose', "color": '#ee92a4'},
    {"brand": "Floriani", "number": 'PF 161', "name": 'Rosewater', "color": '#f4ddd3'},
    {"brand": "Floriani", "number": 'PF 1020', "name": 'Pink Mist', "color": '#f4e2de'},
    {"brand": "Floriani", "number": 'PF 1510', "name": 'Bubblegum', "color": '#fcbfc0'},
    {"brand": "Floriani", "number": 'PF 1514', "name": 'Light Bronze', "color": '#e04236'},
    {"brand": "Floriani", "number": 'PF 1545', "name": 'Cotton Candy', "color": '#de6476'},
    {"brand": "Floriani", "number": 'PF 1898', "name": 'Orchid Ice', "color": '#f5e2e4'},
    {"brand": "Floriani", "number": 'PF 1603', "name": 'Dark Mulberry', "color": '#a53543'},
    {"brand": "Floriani", "number": 'PF 1602', "name": 'Cameo', "color": '#bf535d'},
    {"brand": "Floriani", "number": 'PF 1600', "name": 'Light Mulberry', "color": '#e77d7f'},
    {"brand": "Floriani", "number": 'PF 101', "name": 'Pale Pink', "color": '#f3e9ee'},
    {"brand": "Floriani", "number": 'PF 102', "name": 'Light Pink', "color": '#f5d6e4'},
    {"brand": "Floriani", "number": 'PF 103', "name": 'Pink', "color": '#fda5b9'},
    {"brand": "Floriani", "number": 'PF 104', "name": 'Rosetta', "color": '#f77e9a'},
    {"brand": "Floriani", "number": 'PF 105', "name": 'Laurel Pink', "color": '#ef4b75'},
    {"brand": "Floriani", "number": 'PF 106', "name": 'Dark Pink', "color": '#ee476c'},
    {"brand": "Floriani", "number": 'PF 123', "name": 'Pink Mist', "color": '#f3d9e6'},
    {"brand": "Floriani", "number": 'PF 125', "name": 'Bright Pink', "color": '#f88aa9'},
    {"brand": "Floriani", "number": 'PF 127', "name": 'Hot Pink', "color": '#eb386c'},
    {"brand": "Floriani", "number": 'PF 128', "name": 'Scorching Pink', "color": '#e93068'},
    {"brand": "Floriani", "number": 'PF 129', "name": 'Deep Pink', "color": '#c4113c'},
    {"brand": "Floriani", "number": 'PF 137', "name": 'Fandango', "color": '#8f194a'},
    {"brand": "Floriani", "number": 'PF 135', "name": 'Renaissance', "color": '#b42e66'},
    {"brand": "Floriani", "number": 'PF 133', "name": 'Powder Puff', "color": '#c46790'},
    {"brand": "Floriani", "number": 'PF 131', "name": 'Light Lilac', "color": '#ecb7ce'},
    {"brand": "Floriani", "number": 'PF 1122', "name": 'Marie Antoinette', "color": '#bc222c'},
    {"brand": "Floriani", "number": 'PF 1121', "name": 'China Rose', "color": '#c72635'},
    {"brand": "Floriani", "number": 'PF 1120', "name": 'Lafayette Rose', "color": '#dd2e4b'},
    {"brand": "Floriani", "number": 'PF 1119', "name": 'Impatients', "color": '#f26374'},
    {"brand": "Floriani", "number": 'PF 117', "name": 'Misty Pink', "color": '#fdbac0'},
    {"brand": "Floriani", "number": 'PF 116', "name": 'Peach Blossom', "color": '#f5e4e2'},
    {"brand": "Floriani", "number": 'PF 180', "name": 'Pink Flesh', "color": '#fac7b1'},
    {"brand": "Floriani", "number": 'PF 1011', "name": 'Rose Carolina', "color": '#fbd1cf'},
    {"brand": "Floriani", "number": 'PF 1013', "name": 'Iceland', "color": '#f25f72'},
    {"brand": "Floriani", "number": 'PF 1014', "name": 'Dusty Rose', "color": '#ef5367'},
    {"brand": "Floriani", "number": 'PF 1182', "name": 'Currant', "color": '#b62f3a'},
    {"brand": "Floriani", "number": 'PF 1586', "name": 'Cabernet', "color": '#9a1422'},
    {"brand": "Floriani", "number": 'PF 186', "name": 'Copper', "color": '#e62627'},
    {"brand": "Floriani", "number": 'PF 184', "name": 'Salmon', "color": '#ef4b48'},
    {"brand": "Floriani", "number": 'PF 182', "name": 'Misty Maize', "color": '#f8776e'},
    {"brand": "Floriani", "number": 'PF 249', "name": 'Mitchell Green', "color": '#37523c'},
    {"brand": "Floriani", "number": 'PF 259', "name": 'Grey Wool', "color": '#2d4538'},
    {"brand": "Floriani", "number": 'PF 298', "name": 'Dark Army Green', "color": '#34524c'},
    {"brand": "Floriani", "number": 'PF 2417', "name": 'Dark Grey/Green', "color": '#425c45'},
    {"brand": "Floriani", "number": 'PF 2015', "name": 'Patio Green', "color": '#545722'},
    {"brand": "Floriani", "number": 'PF 2013', "name": 'Avacado', "color": '#6e7b28'},
    {"brand": "Floriani", "number": 'PF 2011', "name": 'Light Olive', "color": '#a0a53f'},
    {"brand": "Floriani", "number": 'PF 253', "name": 'Pale Green', "color": '#4ab389'},
    {"brand": "Floriani", "number": 'PF 252', "name": 'Spearmint', "color": '#cddebd'},
    {"brand": "Floriani", "number": 'PF 251', "name": 'Flite Green', "color": '#f4fdc4'},
    {"brand": "Floriani", "number": 'PF 238', "name": 'Olive Drab', "color": '#6d9041'},
    {"brand": "Floriani", "number": 'PF 237', "name": 'Bean Green', "color": '#75853d'},
    {"brand": "Floriani", "number": 'PF 236', "name": 'Ashen Green', "color": '#c4c67a'},
    {"brand": "Floriani", "number": 'PF 255', "name": 'Evergreen', "color": '#1c8768'},
    {"brand": "Floriani", "number": 'PF 257', "name": 'Holly Green', "color": '#4d513f'},
    {"brand": "Floriani", "number": 'PF 200', "name": 'True Green', "color": '#066d42'},
    {"brand": "Floriani", "number": 'PF 233', "name": 'Irish Green', "color": '#077f4a'},
    {"brand": "Floriani", "number": 'PF 232', "name": 'Spring Green', "color": '#049745'},
    {"brand": "Floriani", "number": 'PF 231', "name": 'Sour Apple', "color": '#46ab4d'},
    {"brand": "Floriani", "number": 'PF 229', "name": 'Lime', "color": '#5bb54e'},
    {"brand": "Floriani", "number": 'PF 228', "name": 'Cape Green', "color": '#b8df69'},
    {"brand": "Floriani", "number": 'PF 223', "name": 'Dark Teal', "color": '#206e69'},
    {"brand": "Floriani", "number": 'PF 292', "name": 'Peppermint', "color": '#1e6c64'},
    {"brand": "Floriani", "number": 'PF 293', "name": 'Blue Spruce', "color": '#154b46'},
    {"brand": "Floriani", "number": 'PF 261', "name": 'Mint', "color": '#8ed4ad'},
    {"brand": "Floriani", "number": 'PF 262', "name": 'Nile', "color": '#37ac74'},
    {"brand": "Floriani", "number": 'PF 263', "name": 'Pale Jade', "color": '#1aa26e'},
    {"brand": "Floriani", "number": 'PF 245', "name": 'Woodland Green', "color": '#729c5e'},
    {"brand": "Floriani", "number": 'PF 244', "name": 'Celery', "color": '#bcd898'},
    {"brand": "Floriani", "number": 'PF 243', "name": 'Winter Spring', "color": '#ddf5c8'},
    {"brand": "Floriani", "number": 'PF 266', "name": 'Emerald Green', "color": '#0e4437'},
    {"brand": "Floriani", "number": 'PF 265', "name": 'Dinosaur Green', "color": '#0d5a41'},
    {"brand": "Floriani", "number": 'PF 264', "name": 'Medium Green', "color": '#0d7f54'},
    {"brand": "Floriani", "number": 'PF 248', "name": 'Hunter Green', "color": '#5c6c42'},
    {"brand": "Floriani", "number": 'PF 247', "name": 'Ivy', "color": '#576b3c'},
    {"brand": "Floriani", "number": 'PF 205', "name": 'Willow Green', "color": '#11573a'},
    {"brand": "Floriani", "number": 'PF 203', "name": 'Moss', "color": '#608c6f'},
    {"brand": "Floriani", "number": 'PF 201', "name": 'Seafrost', "color": '#91b896'},
    {"brand": "Floriani", "number": 'PF 218', "name": 'Maui Green', "color": '#584c16'},
    {"brand": "Floriani", "number": 'PF 214', "name": 'Basil', "color": '#776218'},
    {"brand": "Floriani", "number": 'PF 210', "name": 'Miranda Green', "color": '#9c872b'},
    {"brand": "Floriani", "number": 'PF 206', "name": 'Wreath Green', "color": '#274421'},
    {"brand": "Floriani", "number": 'PF 296', "name": 'Granite', "color": '#4f5f54'},
    {"brand": "Floriani", "number": 'PF K33', "name": 'Blue Harmony', "color": '#53bbc8'},
    {"brand": "Floriani", "number": 'PF K37', "name": 'Agua', "color": '#2b8887'},
    {"brand": "Floriani", "number": 'PF P52', "name": 'Mediterranean', "color": '#379aa6'},
    {"brand": "Floriani", "number": 'PF 074', "name": 'Medieval Teal', "color": '#1d5257'},
    {"brand": "Floriani", "number": 'PF 219', "name": 'Green Mist', "color": '#a6dfd6'},
    {"brand": "Floriani", "number": 'PF 220', "name": 'Wintergreen', "color": '#68c5bc'},
    {"brand": "Floriani", "number": 'PF 221', "name": 'Neptune', "color": '#25897c'},
    {"brand": "Floriani", "number": 'PF 222', "name": 'Teal', "color": '#21766d'},
    {"brand": "Floriani", "number": 'PF 291', "name": 'Seafoam', "color": '#5dbeba'},
    {"brand": "Floriani", "number": 'PF 294', "name": 'Pine Green', "color": '#262e37'},
    {"brand": "Floriani", "number": 'PF 342', "name": 'Slate Blue', "color": '#5c777a'},
    {"brand": "Floriani", "number": 'PF 277', "name": 'Green Meadow', "color": '#5b6834'},
    {"brand": "Floriani", "number": 'PF 275', "name": 'Mineral Green', "color": '#a4b948'},
    {"brand": "Floriani", "number": 'PF 273', "name": 'Key Lime', "color": '#b9cf4f'},
    {"brand": "Floriani", "number": 'PF 285', "name": 'Parsley', "color": '#867b20'},
    {"brand": "Floriani", "number": 'PF 284', "name": 'Scotch Green', "color": '#b29f20'},
    {"brand": "Floriani", "number": 'PF 283', "name": 'Green Gold', "color": '#cec534'},
    {"brand": "Floriani", "number": 'PF 369', "name": 'Blue Frost', "color": '#8bd3e4'},
    {"brand": "Floriani", "number": 'PF 370', "name": 'Mint Julep', "color": '#48abcd'},
    {"brand": "Floriani", "number": 'PF 371', "name": 'Tahoe Blue', "color": '#4ca2d3'},
    {"brand": "Floriani", "number": 'PF 372', "name": 'Blue Pacific', "color": '#4886c2'},
    {"brand": "Floriani", "number": 'PF 373', "name": 'California Blue', "color": '#3f73aa'},
    {"brand": "Floriani", "number": 'PF 357', "name": 'Navy Blue', "color": '#201c49'},
    {"brand": "Floriani", "number": 'PF 358', "name": 'Navy Satin', "color": '#1f143b'},
    {"brand": "Floriani", "number": 'PF 360', "name": 'Dark Navy', "color": '#210f1a'},
    {"brand": "Floriani", "number": 'PF 358S', "name": 'Midnight Navy', "color": '#40425f'},
    {"brand": "Floriani", "number": 'PF 361', "name": 'Light Blue', "color": '#ceeef2'},
    {"brand": "Floriani", "number": 'PF 362', "name": 'Pastel Blue', "color": '#4ea9d9'},
    {"brand": "Floriani", "number": 'PF 363', "name": 'Twinkle Blue', "color": '#4c92ce'},
    {"brand": "Floriani", "number": 'PF 364', "name": 'Starlight Blue', "color": '#386395'},
    {"brand": "Floriani", "number": 'PF 365', "name": 'Medium Blue', "color": '#3c669e'},
    {"brand": "Floriani", "number": 'PF 366', "name": 'Bluejay', "color": '#2e4075'},
    {"brand": "Floriani", "number": 'PF 367', "name": 'Blueberry', "color": '#2e4176'},
    {"brand": "Floriani", "number": 'PF 368', "name": 'Royal Blue', "color": '#231a55'},
    {"brand": "Floriani", "number": 'PF K07', "name": 'Sky Blue', "color": '#3e72a7'},
    {"brand": "Floriani", "number": 'PF 335', "name": 'Midnight Blue', "color": '#1c1d43'},
    {"brand": "Floriani", "number": 'PF 334', "name": 'Concord Blue', "color": '#223358'},
    {"brand": "Floriani", "number": 'PF 333', "name": 'Baltic Blue', "color": '#2a4a71'},
    {"brand": "Floriani", "number": 'PF 332', "name": 'Periwinkle', "color": '#3e75a6'},
    {"brand": "Floriani", "number": 'PF 055', "name": 'Pristine Blue', "color": '#2a396c'},
    {"brand": "Floriani", "number": 'PF 007', "name": 'Oriental Blue', "color": '#406ea9'},
    {"brand": "Floriani", "number": 'PF 306', "name": 'Imperial Blue', "color": '#115b8f'},
    {"brand": "Floriani", "number": 'PF 352', "name": 'Moderate Blue', "color": '#a9cfe6'},
    {"brand": "Floriani", "number": 'PF 3103', "name": 'Medium Green/Blue', "color": '#30607b'},
    {"brand": "Floriani", "number": 'PF 3335', "name": 'Blue Dusk', "color": '#325f97'},
    {"brand": "Floriani", "number": 'PF 3433', "name": 'Pretty Blue', "color": '#007aa8'},
    {"brand": "Floriani", "number": 'PF 3435', "name": 'Deep Ocean', "color": '#006195'},
    {"brand": "Floriani", "number": 'PF 3763', "name": 'Baby Blue', "color": '#84a1ce'},
    {"brand": "Floriani", "number": 'PF 308', "name": 'Dark Blue', "color": '#222754'},
    {"brand": "Floriani", "number": 'PF 307', "name": 'Rocket Blue', "color": '#232f5a'},
    {"brand": "Floriani", "number": 'PF 344', "name": 'Pilgrim Blue', "color": '#2e2f34'},
    {"brand": "Floriani", "number": 'PF 314', "name": 'Federal Blue', "color": '#315a6a'},
    {"brand": "Floriani", "number": 'PF 312', "name": 'Gettysburg', "color": '#368ca4'},
    {"brand": "Floriani", "number": 'PF 310', "name": 'Colony Blue', "color": '#5ab3c6'},
    {"brand": "Floriani", "number": 'PF 378', "name": 'Deep Sea Turquiose', "color": '#007b94'},
    {"brand": "Floriani", "number": 'PF 376', "name": 'Indian Ocean', "color": '#0094ab'},
    {"brand": "Floriani", "number": 'PF 385', "name": 'Niagara', "color": '#006881'},
    {"brand": "Floriani", "number": 'PF 384', "name": 'Cascade', "color": '#0085b0'},
    {"brand": "Floriani", "number": 'PF 383', "name": 'Venice Blue', "color": '#aceef9'},
    {"brand": "Floriani", "number": 'PF 3657', "name": 'Wonder Blue', "color": '#4b6fa2'},
    {"brand": "Floriani", "number": 'PF 3761', "name": 'Blue Hint', "color": '#bed0e4'},
    {"brand": "Floriani", "number": 'PF 3764', "name": 'Parisian Blue', "color": '#667bac'},
    {"brand": "Floriani", "number": 'PF 3871', "name": 'Cosmic Sky', "color": '#8d99c3'},
    {"brand": "Floriani", "number": 'PF 3877', "name": 'Dusty Navy', "color": '#485581'},
    {"brand": "Floriani", "number": 'PF 3878', "name": 'Dark Navy', "color": '#363d5c'},
    {"brand": "Floriani", "number": 'PF 453', "name": 'Dark Taupe', "color": '#604a46'},
    {"brand": "Floriani", "number": 'PF 2040', "name": 'Blue Azure', "color": '#009999'},
    {"brand": "Floriani", "number": 'PF 2042', "name": 'Aquamarine', "color": '#00979b'},
    {"brand": "Floriani", "number": 'PF 391', "name": 'Beryl Blue', "color": '#008191'},
    {"brand": "Floriani", "number": 'PF 392', "name": 'Honey Bird', "color": '#006774'},
    {"brand": "Floriani", "number": 'PF 393', "name": 'Italian Blue', "color": '#00434b'},
    {"brand": "Floriani", "number": 'PF 501', "name": 'Lemon', "color": '#f5e27c'},
    {"brand": "Floriani", "number": 'PF 502', "name": 'Dandelion', "color": '#f8be5b'},
    {"brand": "Floriani", "number": 'PF 503', "name": 'Sunflower', "color": '#f29a4c'},
    {"brand": "Floriani", "number": 'PF 512', "name": 'Jasmine', "color": '#fe8342'},
    {"brand": "Floriani", "number": 'PF 514', "name": 'Golden Glow', "color": '#d25a34'},
    {"brand": "Floriani", "number": 'PF 516', "name": 'Autumn Gold', "color": '#e56c38'},
    {"brand": "Floriani", "number": 'PF 523', "name": 'Goldenrod', "color": '#ffc446'},
    {"brand": "Floriani", "number": 'PF 522', "name": 'Straw', "color": '#ffe564'},
    {"brand": "Floriani", "number": 'PF 521', "name": 'Cornsilk', "color": '#fff4a2'},
    {"brand": "Floriani", "number": 'PF 544', "name": 'Amber Yellow', "color": '#ffe02b'},
    {"brand": "Floriani", "number": 'PF 542', "name": 'Cockatoo', "color": '#fff266'},
    {"brand": "Floriani", "number": 'PF 540', "name": 'Cream', "color": '#fff6cb'},
    {"brand": "Floriani", "number": 'PF 571', "name": 'Pale Peach', "color": '#ece2b1'},
    {"brand": "Floriani", "number": 'PF 578', "name": 'Volunteer', "color": '#d57226'},
    {"brand": "Floriani", "number": 'PF 591', "name": 'Shell', "color": '#f1e2c6'},
    {"brand": "Floriani", "number": 'PF 594', "name": 'Pale Orange', "color": '#f7b070'},
    {"brand": "Floriani", "number": 'PF 595', "name": 'Apricot', "color": '#f2944e'},
    {"brand": "Floriani", "number": 'PF 6655', "name": 'Ophelia', "color": '#42071c'},
    {"brand": "Floriani", "number": 'PF 654', "name": 'Orchid', "color": '#79233f'},
    {"brand": "Floriani", "number": 'PF 653', "name": 'Spring Beauty', "color": '#c97fa4'},
    {"brand": "Floriani", "number": 'PF 526', "name": 'Bijol', "color": '#ff6634'},
    {"brand": "Floriani", "number": 'PF 525', "name": 'Athletic Gold', "color": '#ff9e44'},
    {"brand": "Floriani", "number": 'PF 524', "name": 'Old Athletic Gold', "color": '#ffb33c'},
    {"brand": "Floriani", "number": 'PF 605', "name": 'Grape', "color": '#650736'},
    {"brand": "Floriani", "number": 'PF 603', "name": 'Plum Pewter', "color": '#740e48'},
    {"brand": "Floriani", "number": 'PF 635', "name": 'Arab Plum', "color": '#36192e'},
    {"brand": "Floriani", "number": 'PF 546', "name": 'Snapdragon', "color": '#ffe732'},
    {"brand": "Floriani", "number": 'PF 531', "name": 'Vanilla', "color": '#fffccd'},
    {"brand": "Floriani", "number": 'PF 532', "name": 'Sunrise', "color": '#ffc467'},
    {"brand": "Floriani", "number": 'PF 533', "name": 'Apricot', "color": '#ffb148'},
    {"brand": "Floriani", "number": 'PF 534', "name": 'Pumpkin', "color": '#ff8435'},
    {"brand": "Floriani", "number": 'PF 535', "name": 'Golden Poppy', "color": '#ff783b'},
    {"brand": "Floriani", "number": 'PF 537', "name": 'Carrot', "color": '#ff5528'},
    {"brand": "Floriani", "number": 'PF 565', "name": 'Harvest', "color": '#795113'},
    {"brand": "Floriani", "number": 'PF 564', "name": 'Bran', "color": '#af6215'},
    {"brand": "Floriani", "number": 'PF 563', "name": 'Old Gold', "color": '#c06218'},
    {"brand": "Floriani", "number": 'PF 562', "name": 'Walnut Taffy', "color": '#eb912c'},
    {"brand": "Floriani", "number": 'PF 561', "name": 'Old Ivory', "color": '#ffb73e'},
    {"brand": "Floriani", "number": 'PF 560', "name": 'Blonde Straw', "color": '#ffde63'},
    {"brand": "Floriani", "number": 'PF 421', "name": 'Wood Ash', "color": '#e1d1a1'},
    {"brand": "Floriani", "number": 'PF 422', "name": 'Lime Gray', "color": '#ae9860'},
    {"brand": "Floriani", "number": 'PF 423', "name": 'Earth Gray', "color": '#97844f'},
    {"brand": "Floriani", "number": 'PF 792', "name": 'Shasta Pink', "color": '#e8b9a0'},
    {"brand": "Floriani", "number": 'PF 794', "name": 'Flagstone Clay', "color": '#a86547'},
    {"brand": "Floriani", "number": 'PF 796', "name": 'Provincial Rose', "color": '#7d3421'},
    {"brand": "Floriani", "number": 'PF 661', "name": 'Light Violet', "color": '#9a7fb9'},
    {"brand": "Floriani", "number": 'PF 676', "name": 'Royal Purple', "color": '#541c49'},
    {"brand": "Floriani", "number": 'PF 675', "name": 'Luxury', "color": '#772271'},
    {"brand": "Floriani", "number": 'PF 674', "name": 'Russian Violet', "color": '#7a68ae'},
    {"brand": "Floriani", "number": 'PF 673', "name": 'Lavender', "color": '#934e90'},
    {"brand": "Floriani", "number": 'PF 672', "name": 'Amethyst', "color": '#cebad8'},
    {"brand": "Floriani", "number": 'PF 755', "name": 'Burnt Orange', "color": '#e2501f'},
    {"brand": "Floriani", "number": 'PF 753', "name": 'Orange Peel', "color": '#e6913c'},
    {"brand": "Floriani", "number": 'PF 752', "name": 'Aurora Orange', "color": '#e9a34c'},
    {"brand": "Floriani", "number": 'PF 601', "name": 'Zephyr', "color": '#d86392'},
    {"brand": "Floriani", "number": 'PF 632', "name": 'Grape Ice', "color": '#865e6d'},
    {"brand": "Floriani", "number": 'PF 616', "name": 'Tyrian Blue', "color": '#392d54'},
    {"brand": "Floriani", "number": 'PF 614', "name": 'Slate Lilac', "color": '#5a5c84'},
    {"brand": "Floriani", "number": 'PF 612', "name": 'Lilac Blue', "color": '#869cb8'},
    {"brand": "Floriani", "number": 'PF K38', "name": 'Deep Violet Purple', "color": '#450a72'},
    {"brand": "Floriani", "number": 'PF 665', "name": 'Deep Violet', "color": '#501a75'},
    {"brand": "Floriani", "number": 'PF 663', "name": 'Violet', "color": '#7d509b'},
    {"brand": "Floriani", "number": 'PF 751', "name": 'Sweet Melon', "color": '#e9b058'},
    {"brand": "Floriani", "number": 'PF 723', "name": 'Birch', "color": '#d0ac66'},
    {"brand": "Floriani", "number": 'PF 721', "name": 'Golden Sand', "color": '#e8d790'},
    {"brand": "Floriani", "number": 'PF 769', "name": 'Dark Cinnamon', "color": '#802512'},
    {"brand": "Floriani", "number": 'PF 767', "name": 'Muted Spice', "color": '#c8754a'},
    {"brand": "Floriani", "number": 'PF 765', "name": 'Satin Sheet', "color": '#fddac6'},
    {"brand": "Floriani", "number": 'PF 626', "name": 'Deep Iris', "color": '#753774'},
    {"brand": "Floriani", "number": 'PF 624', "name": 'Afterglow', "color": '#a97baf'},
    {"brand": "Floriani", "number": 'PF 622', "name": 'Geisha', "color": '#c5c0e3'},
    {"brand": "Floriani", "number": 'PF 687', "name": 'Violet Blue', "color": '#704c9a'},
    {"brand": "Floriani", "number": 'PF 688', "name": 'Grape Jelly', "color": '#553783'},
    {"brand": "Floriani", "number": 'PF 689', "name": 'Concord Grape', "color": '#3d2256'},
    {"brand": "Floriani", "number": 'PF 811', "name": 'Angora White', "color": '#f3ebcf'},
    {"brand": "Floriani", "number": 'PF 813', "name": 'Frontier Tan', "color": '#bfb789'},
    {"brand": "Floriani", "number": 'PF 815', "name": 'Deep Clay', "color": '#b29f62'},
    {"brand": "Floriani", "number": 'PF 844', "name": 'African Safari', "color": '#9a713a'},
    {"brand": "Floriani", "number": 'PF 842', "name": 'Willow Leaf', "color": '#d5c68d'},
    {"brand": "Floriani", "number": 'PF 783', "name": 'Sahara Tan', "color": '#efab79'},
    {"brand": "Floriani", "number": 'PF 784', "name": 'Light Sienna', "color": '#c9662e'},
    {"brand": "Floriani", "number": 'PF 785', "name": 'Sienna Brown', "color": '#b54a1f'},
    {"brand": "Floriani", "number": 'PF 786', "name": 'Berkshire Brick', "color": '#ad3d1b'},
    {"brand": "Floriani", "number": 'PF 711', "name": 'Inca Gold', "color": '#db7525'},
    {"brand": "Floriani", "number": 'PF 713', "name": 'Antique Bronze', "color": '#99370f'},
    {"brand": "Floriani", "number": 'PF 715', "name": 'Jamoca', "color": '#7c221a'},
    {"brand": "Floriani", "number": 'PF 694', "name": 'Viking Purple', "color": '#7b2175'},
    {"brand": "Floriani", "number": 'PF 695', "name": 'Purple Passion', "color": '#5f2373'},
    {"brand": "Floriani", "number": 'PF 696', "name": 'Regal Purple', "color": '#4c1654'},
    {"brand": "Floriani", "number": 'PF 737', "name": 'Indian Spice', "color": '#945f32'},
    {"brand": "Floriani", "number": 'PF 735', "name": 'Aztec Tan', "color": '#deb76b'},
    {"brand": "Floriani", "number": 'PF 734', "name": 'Oak Buff', "color": '#f0d798'},
    {"brand": "Floriani", "number": 'PF 733', "name": 'Sudan', "color": '#f3e8b8'},
    {"brand": "Floriani", "number": 'PF 731', "name": 'Sandstone', "color": '#f5f6e4'},
    {"brand": "Floriani", "number": 'PF 730', "name": 'Off White', "color": '#fdfcfc'},
    {"brand": "Floriani", "number": 'PF 195', "name": 'Russet', "color": '#932039'},
    {"brand": "Floriani", "number": 'PF 199', "name": 'Chocolate', "color": '#61323b'},
    {"brand": "Floriani", "number": 'PF 4352', "name": 'Dark Grey/Blue', "color": '#716e79'},
    {"brand": "Floriani", "number": 'PF 4613', "name": 'Storm', "color": '#868382'},
    {"brand": "Floriani", "number": 'PF 720', "name": 'Tutledove', "color": '#ece5d5'},
    {"brand": "Floriani", "number": 'PF 778', "name": 'Amber Beige', "color": '#714b3f'},
    {"brand": "Floriani", "number": 'PF 779', "name": 'Dark Grey', "color": '#584643'},
    {"brand": "Floriani", "number": 'PF 7986', "name": 'Brown Stone', "color": '#5b423a'},
    {"brand": "Floriani", "number": 'PF 809', "name": 'Nude Gold', "color": '#e0ccb5'},
    {"brand": "Floriani", "number": 'PF 485', "name": 'Gray', "color": '#788285'},
    {"brand": "Floriani", "number": 'PF 484', "name": 'Country Gray', "color": '#748c8d'},
    {"brand": "Floriani", "number": 'PF 483', "name": 'Light Gray', "color": '#ccdada'},
    {"brand": "Floriani", "number": 'PF 741', "name": 'Pottery Buff', "color": '#eab67f'},
    {"brand": "Floriani", "number": 'PF 743', "name": 'Old World Buff', "color": '#d3965b'},
    {"brand": "Floriani", "number": 'PF 745', "name": 'Harvest Brown', "color": '#95552a'},
    {"brand": "Floriani", "number": 'PF 749', "name": 'Mahogany', "color": '#42241d'},
    {"brand": "Floriani", "number": 'PF 739', "name": 'Cleveland', "color": '#4a321e'},
    {"brand": "Floriani", "number": 'PF 738', "name": 'Arab Tan', "color": '#a54126'},
    {"brand": "Floriani", "number": 'PF 4', "name": 'Indian Orange', "color": '#ffcc1e'},
    {"brand": "Floriani", "number": 'PF 3', "name": 'Neon Red', "color": '#f93a2b'},
    {"brand": "Floriani", "number": 'PF 2', "name": 'Firefly', "color": '#fc2366'},
    {"brand": "Floriani", "number": 'PF 1', "name": 'Neon Radiance', "color": '#fc2366'},
    {"brand": "Floriani", "number": 'PF 801', "name": 'Ice Cap', "color": '#fafbfb'},
    {"brand": "Floriani", "number": 'PF 800', "name": 'Pure White', "color": '#fbfdfc'},
    {"brand": "Floriani", "number": 'PF 10', "name": 'Neon Citron', "color": '#dde00f'},
    {"brand": "Floriani", "number": 'PF 9', "name": 'Safety Yellow', "color": '#dde00f'},
    {"brand": "Floriani", "number": 'PF 8', "name": 'Bermuda Pink', "color": '#ff0093'},
    {"brand": "Floriani", "number": 'PF 6', "name": 'Neon Pink', "color": '#ff0093'},
    {"brand": "Floriani", "number": 'PF 5', "name": 'Neon Orange', "color": '#ff7f1e'},
    {"brand": "Floriani", "number": 'PF 850', "name": 'Lamp Light', "color": '#fdfcfc'},
    {"brand": "Floriani", "number": 'PF 13', "name": 'Viridian Green', "color": '#60dd49'},
    {"brand": "Floriani", "number": 'PF 14', "name": 'Midori Green', "color": '#60dd49'},
    {"brand": "Floriani", "number": 'PF 17', "name": 'Dreamsicle', "color": '#ff9338'},
    {"brand": "Floriani", "number": 'PF 18', "name": 'Navaho Orange', "color": '#ff5416'},
    {"brand": "Floriani", "number": 'PF 900', "name": 'Black', "color": '#000000'},
    {"brand": "Floriani", "number": 'PF 11', "name": 'Chalcedony Yellow', "color": '#ffd816'},
    {"brand": "Floriani", "number": 'PF 433', "name": 'Pale Sterling Grey', "color": '#c3c0c3'},
    {"brand": "Floriani", "number": 'PF 461', "name": 'Chrome', "color": '#b4bbc3'},
    {"brand": "Floriani", "number": 'PF 4251', "name": 'Medium Grey', "color": '#afa8a5'},
    {"brand": "Floriani", "number": 'PF 462', "name": 'Silver', "color": '#959ba3'},
    {"brand": "Floriani", "number": 'PF 6351', "name": 'Ocean Blue', "color": '#9a90a8'},
    {"brand": "Floriani", "number": 'PF 6502', "name": 'Light Brown', "color": '#a48d97'},
    {"brand": "Floriani", "number": 'PF 6504', "name": 'Gun Metal Gray', "color": '#836a7d'},
    {"brand": "Floriani", "number": 'PF 139', "name": 'Medium Purple', "color": '#65254b'},
    {"brand": "Floriani", "number": 'PF 1608', "name": 'Rose Dust', "color": '#9e758e'},
    {"brand": "Floriani", "number": 'PF 1609', "name": 'Intense Maroon', "color": '#5a3341'},
    {"brand": "Floriani", "number": 'PF 4321', "name": 'Pearl', "color": '#cfc9c1'},
    {"brand": "Floriani", "number": 'PF 600', "name": 'Viola', "color": '#ceaccf'},
    {"brand": "Floriani", "number": 'PF 633', "name": 'Cadet', "color": '#7a6984'},
    {"brand": "Floriani", "number": 'PF 634', "name": 'Mulled Grape', "color": '#6d5d7f'},
    {"brand": "Floriani", "number": 'PF 652', "name": 'Haze', "color": '#dac1d1'},
    {"brand": "Floriani", "number": 'PF 7983', "name": 'Medium Brown', "color": '#9f8382'},
    {"brand": "Floriani", "number": 'PF 486', "name": 'Slate Gray', "color": '#4d4344'},
    {"brand": "Floriani", "number": 'PF 487', "name": 'Gun Metal Gray', "color": '#555553'},
    {"brand": "Floriani", "number": 'PF 488', "name": 'Dark Gray', "color": '#3b3539'},
    {"brand": "Floriani", "number": 'PF 489', "name": 'Charcoal Gray', "color": '#322326'},
    {"brand": "Floriani", "number": 'PF 451', "name": 'Light Taupe', "color": '#bf9a8c'},
    {"brand": "Floriani", "number": 'PF 452', "name": 'Taupe', "color": '#89716a'},
    {"brand": "Floriani", "number": 'PF 6001', "name": 'Princess', "color": '#e4c9dc'},
    {"brand": "Floriani", "number": 'PF 6354', "name": 'Steel', "color": '#9a5a79'},
    {"brand": "Floriani", "number": 'PF 6657', "name": 'Dark Purple', "color": '#593859'},
    {"brand": "Floriani", "number": 'PF 434', "name": 'Pewter', "color": '#7aa3a1'},
    {"brand": "Floriani", "number": 'PF 436', "name": 'Graphite', "color": '#272a2a'},
    {"brand": "Floriani", "number": 'PF 416', "name": 'Penguin', "color": '#38382f'},
    {"brand": "Floriani", "number": 'PF 415', "name": 'Westpoint', "color": '#524737'},
    {"brand": "Floriani", "number": 'PF 413', "name": 'Old Silver', "color": '#7d775d'},
    {"brand": "Floriani", "number": 'PF 411', "name": 'Palm Leaf', "color": '#bcb7a0'},
]


THREAD_CATALOGS = {
    "Floriani": FLORIANI_THREADS,
    "Madeira": MADEIRA_THREADS,
}


def available_thread_brands() -> list[str]:
    return list(THREAD_CATALOGS)


def load_thread_catalog(brand: str | None = None) -> list[dict]:
    if brand in THREAD_CATALOGS:
        return [dict(item) for item in THREAD_CATALOGS[brand]]
    return [dict(item) for catalog in THREAD_CATALOGS.values() for item in catalog]
